name: Run Fibonacci Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Fibonacci script
      run: |
        git clone https://github.com/NITHIN-K-BHAT/connect-one.git
        cd connect-one
        python fibonacci.py <<EOF
        10
        EOF
